# Generated by Django 4.2.6 on 2023-10-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('display', '0005_extendedgroup_delete_displaygroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendedgroup',
            options={'permissions': (('can_do_something', 'Can do something1'), ('can_do_something_else', 'Ca do something2'))},
        ),
        migrations.AddField(
            model_name='extendedgroup',
            name='extendedPermissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions for this group.', to='auth.permission'),
        ),
    ]
