# Generated by Django 4.2.6 on 2023-10-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_group_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
    ]
